runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: main.app

- url: /assets
  static_dir: frontend/dist/assets
  expiration: '100d'

- url: /js
  static_dir: frontend/dist/js
  expiration: '100d'

- url: /css
  static_dir: frontend/dist/css
  expiration: '100d'

- url: /fonts
  static_dir: frontend/dist/fonts
  expiration: '100d'
  mime_type: application/x-font-otf

- url: /.*
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html

libraries:
- name: webapp2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^.idea$
- ^(.*/)?node_modules$
- ^frontend/src$
